/**
 * TerrainDataProvider - Provides terrain data to collision and game systems
 * 
 * This is a thin wrapper that routes queries to the ChunkBlockCache
 * which contains data generated by the web worker.
 * 
 * The worker is the SINGLE SOURCE OF TRUTH - this class does NOT
 * generate any terrain data itself.
 */

export class TerrainDataProvider {
    constructor(workerManager) {
        this.workerManager = workerManager;
    }
    
    /**
     * Get block type at world coordinates
     * @param {number} x - World X coordinate
     * @param {number} y - World Y coordinate  
     * @param {number} z - World Z coordinate
     * @returns {string|null} Block type name, or null for air/unloaded
     */
    getBlockType(x, y, z) {
        return this.workerManager.getBlockType(x, y, z);
    }
    
    /**
     * Check if a block is solid (for collision)
     * @param {number} x - World X coordinate
     * @param {number} y - World Y coordinate
     * @param {number} z - World Z coordinate
     * @returns {boolean} True if block is solid
     */
    isSolid(x, y, z) {
        const blockType = this.getBlockType(x, y, z);
        if (blockType === null) return false;
        if (blockType === 'water' || blockType === 'water_full') return false;
        return true;
    }
    
    /**
     * Get terrain height at position
     * Note: This scans the block column, which is slightly slower than
     * a dedicated heightmap but ensures consistency with block data.
     * 
     * @param {number} x - World X coordinate
     * @param {number} z - World Z coordinate
     * @returns {number} Height of topmost solid block, or 0 if no data
     */
    getHeight(x, z) {
        const MAX_HEIGHT = 64;
        
        // Scan from top down to find first solid block
        for (let y = MAX_HEIGHT - 1; y >= 0; y--) {
            const blockType = this.getBlockType(x, y, z);
            if (blockType !== null && 
                blockType !== 'water' && 
                blockType !== 'water_full') {
                return y;
            }
        }
        
        return 0;
    }
    
    /**
     * Get interpolated height at any world position
     * Uses bilinear interpolation between the four surrounding block heights
     * @param {number} x - World X coordinate (can be fractional)
     * @param {number} z - World Z coordinate (can be fractional)
     * @returns {number} Interpolated height
     */
    getInterpolatedHeight(x, z) {
        const x0 = Math.floor(x);
        const z0 = Math.floor(z);
        const x1 = x0 + 1;
        const z1 = z0 + 1;
        
        const fx = x - x0;
        const fz = z - z0;
        
        const h00 = this.getHeight(x0, z0);
        const h10 = this.getHeight(x1, z0);
        const h01 = this.getHeight(x0, z1);
        const h11 = this.getHeight(x1, z1);
        
        const h0 = h00 * (1 - fx) + h10 * fx;
        const h1 = h01 * (1 - fx) + h11 * fx;
        
        return h0 * (1 - fz) + h1 * fz;
    }
    
    /**
     * Check if block data is available at a position
     * Useful for checking if terrain is loaded before spawning entities
     */
    isLoaded(x, z) {
        const CHUNK_SIZE = 16;
        const chunkX = Math.floor(x / CHUNK_SIZE);
        const chunkZ = Math.floor(z / CHUNK_SIZE);
        return this.workerManager.hasBlockData(chunkX, chunkZ);
    }
}